
apiVersion: v1
kind: Service
metadata:
  name: mywebsite-service
  labels:
    app: mywebsite
spec:
  type: LoadBalancer
  ports:
  - name: "mywebsite-service"
    port: 8080
    targetPort: 8080
  
  selector:
    app: mywebsite
  